### ISSUE TITLE
Automatically update link in Navbar.svelte based on latest release

### ISSUE THREAD

**Issue by mjovanc** [njord-rs/website#2]
I want to update in `Navbar.svelte` so that it automatically updates the link based on the latest version:

```html
<a href="http://docs.rs/njord/0.1.0/njord">Docs</a>
```

**Comment by mjovanc** [comment]
We can just use /latest/njord instead lol. that was easy fix. But can someone do it?

**Comment by newtoallofthis123** [comment]
Hey! Check the code! It is already fixed :)

![image](https://github.com/njord-rs/website/assets/78465651/1c2703fc-ae5a-47c8-b828-f47822bfe1dd)
